/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CountryAdminRole;

import Business.CountryEnterprise.CountryEnterprise;
import Business.Helper.CardLayoutContainer;
import Business.Helper.Validation;
import Business.Organization.Organization;
import Business.Organization.PoorPeopleOrganization;
import Business.Person.Person;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageCountryUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCountryUserJPanel
     */
    private JPanel userProcessContainer;
    private CountryEnterprise objCountryEnterprise;
    private String firstName, lastName;

    public ManageCountryUserJPanel(JPanel userProcessContainerPassed,
            CountryEnterprise objCountryEnterprisePassed) {

        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objCountryEnterprise = objCountryEnterprisePassed;

        populateCountryOrgComboBox();
        populateCountryOrgUserComboBox();
    }

    public void populateCountryOrgComboBox() {

        countryOrgJComboBox.removeAllItems();

        for (Organization objOrganization : objCountryEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            countryOrgJComboBox.addItem(objOrganization);
        }
    }

    public void populateCountryOrgUserComboBox() {

        addUserJComboBox.removeAllItems();

        for (Organization objOrganization : objCountryEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            if (!(objOrganization instanceof PoorPeopleOrganization)) {
                addUserJComboBox.addItem(objOrganization);
            }
        }
    }

    public void populateOrgUserTable(Organization objOrganizationPassed) {

        DefaultTableModel dtm = (DefaultTableModel) userJTable.getModel();
        dtm.setRowCount(0);

        for (Person objPerson : objOrganizationPassed.getObjPersonDirectory().getPersonList()) {

            Object row[] = new Object[2];
            row[0] = objPerson.getPersonID();
            row[1] = objPerson;

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        orgJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        countryOrgJComboBox = new javax.swing.JComboBox();
        title1JLabel = new javax.swing.JLabel();
        orgNameJLabel = new javax.swing.JLabel();
        addUserJComboBox = new javax.swing.JComboBox();
        firstNameJLabel = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        lastNameJLabel = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        addUserJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setText("Manage Persons/Users");

        orgJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        orgJLabel.setText("Organization");

        userJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userJTable);
        if (userJTable.getColumnModel().getColumnCount() > 0) {
            userJTable.getColumnModel().getColumn(0).setResizable(false);
            userJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        countryOrgJComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        countryOrgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryOrgJComboBoxActionPerformed(evt);
            }
        });

        title1JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title1JLabel.setText("Add Persons/Users in Organization");

        orgNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        orgNameJLabel.setText("Organization");

        addUserJComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addUserJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserJComboBoxActionPerformed(evt);
            }
        });

        firstNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstNameJLabel.setText("First Name");

        firstNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lastNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lastNameJLabel.setText("Last Name");

        lastNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        addUserJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addUserJButton.setText("Add User");
        addUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orgJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(countryOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backJButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orgNameJLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lastNameJLabel)
                                        .addComponent(firstNameJLabel)))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addUserJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstNameJTextField)
                                    .addComponent(lastNameJTextField)
                                    .addComponent(addUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(title1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgJLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(title1JLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgNameJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameJLabel)
                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addUserJButton)
                .addGap(89, 89, 89)
                .addComponent(backJButton)
                .addGap(149, 149, 149))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void countryOrgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryOrgJComboBoxActionPerformed

        Organization objOrganization = (Organization) countryOrgJComboBox.getSelectedItem();

        if (objOrganization != null) {
            populateOrgUserTable(objOrganization);
        }
    }//GEN-LAST:event_countryOrgJComboBoxActionPerformed

    private void addUserJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserJComboBoxActionPerformed

    private void addUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserJButtonActionPerformed

        //Validation
        boolean validationSuccess;
        validationSuccess = validation();

        if (validationSuccess) {

            Organization objOrganization = (Organization) addUserJComboBox.getSelectedItem();

            if (objOrganization != null) {
                Person objPerson = objOrganization.getObjPersonDirectory().addPerson(objOrganization.getClass().getSimpleName());
                objPerson.setPersonFirstName(firstName);
                objPerson.setPersonLastName(lastName);

                JOptionPane.showMessageDialog(null, "User added successfully!");

                firstNameJTextField.setText(null);
                lastNameJTextField.setText(null);

                countryOrgJComboBox.setSelectedItem(objOrganization);

            }
        }
    }//GEN-LAST:event_addUserJButtonActionPerformed

    private boolean validation() {

        firstName = firstNameJTextField.getText().trim();
        lastName = lastNameJTextField.getText().trim();

        if (Validation.checkForNull(firstName)) {
            JOptionPane.showMessageDialog(null, "Please enter first name");
            firstNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyAlphabets(firstName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper first name. It should contain only alphabets");
            firstNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForNull(lastName)) {
            JOptionPane.showMessageDialog(null, "Please enter last name");
            lastNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyAlphabets(lastName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper last name. It should contain only alphabets");
            lastNameJTextField.requestFocus();
            return false;
        }

        return true;
    }


    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserJButton;
    private javax.swing.JComboBox addUserJComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox countryOrgJComboBox;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JLabel orgJLabel;
    private javax.swing.JLabel orgNameJLabel;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables
}
