/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CountryAdminRole;

import Business.CountryEnterprise.RegSiteEnterprise.RegisteredSiteEnterprise;
import Business.Helper.CardLayoutContainer;
import Business.Helper.UserNameExists;
import Business.Helper.Validation;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.RegSiteAdminRole;
import Business.UserAccount.UserAccount;
import Business.WorldEnterprise;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageRegSiteEntAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRegSiteEntAdminJPanel
     */
    private JPanel userProcessContainer;
    private RegisteredSiteEnterprise objRegisteredSiteEnterprise;
    private WorldEnterprise objWorldEnterprise;
    private String adminFirstName, adminLastName, adminUserName, adminPassword, adminConfirmPassword;
    

    public ManageRegSiteEntAdminJPanel(JPanel userProcessContainerPassed,
            WorldEnterprise objWorldEnterprisePassed, RegisteredSiteEnterprise objRegisteredSiteEnterprisePassed) {

        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objRegisteredSiteEnterprise = objRegisteredSiteEnterprisePassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;

        populateRegSiteAdminTable();
    }

    private void populateRegSiteAdminTable() {

        DefaultTableModel dtm = (DefaultTableModel) regSiteAdminJTable.getModel();
        dtm.setRowCount(0);

        for (Organization objOrganization : objRegisteredSiteEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            if (objOrganization.getClass().getSimpleName().equals(Organization.OrganizationType.RegisteredSiteAdmin.getValue())) {

                for (UserAccount objUserAccount : objOrganization.getObjUserAccountDirectory().getUserAccountList()) {

                    Object row[] = new Object[4];
                    row[0] = objUserAccount.getObjPerson().getPersonID();
                    row[1] = objUserAccount.getObjPerson();
                    row[2] = objUserAccount;
                    row[3] = objUserAccount.getUserAccountStatus();

                    dtm.addRow(row);

                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastNameJLabel = new javax.swing.JLabel();
        userNameJLabel = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        userNameJTextField = new javax.swing.JTextField();
        passJLabel = new javax.swing.JLabel();
        addAdminJButton = new javax.swing.JButton();
        conPassJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        confirmJPasswordField = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        regSiteAdminJTable = new javax.swing.JTable();
        mainJPasswordField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        title1JLabel = new javax.swing.JLabel();
        activateJButton = new javax.swing.JButton();
        firstNameJLabel = new javax.swing.JLabel();
        disableJButton = new javax.swing.JButton();
        firstNameJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lastNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lastNameJLabel.setText("Last Name");

        userNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userNameJLabel.setText("User Name");

        lastNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        userNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        passJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        passJLabel.setText("Password");

        addAdminJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addAdminJButton.setText("Add new Admin");
        addAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminJButtonActionPerformed(evt);
            }
        });

        conPassJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        conPassJLabel.setText("Confirm Password");

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setText("Manage Registered Site Enterprise Admin");

        confirmJPasswordField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        regSiteAdminJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regSiteAdminJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Admin Name", "Admin User Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(regSiteAdminJTable);
        if (regSiteAdminJTable.getColumnModel().getColumnCount() > 0) {
            regSiteAdminJTable.getColumnModel().getColumn(0).setResizable(false);
            regSiteAdminJTable.getColumnModel().getColumn(1).setResizable(false);
            regSiteAdminJTable.getColumnModel().getColumn(2).setResizable(false);
            regSiteAdminJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        mainJPasswordField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        title1JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title1JLabel.setText("Add New Admin");

        activateJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        activateJButton.setText("Activate Account");
        activateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateJButtonActionPerformed(evt);
            }
        });

        firstNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstNameJLabel.setText("First Name");

        disableJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        disableJButton.setText("Disable Account");
        disableJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableJButtonActionPerformed(evt);
            }
        });

        firstNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(titleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(title1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameJLabel)
                                    .addComponent(passJLabel)
                                    .addComponent(conPassJLabel))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addAdminJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mainJPasswordField)
                                    .addComponent(userNameJTextField)
                                    .addComponent(confirmJPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lastNameJLabel)
                            .addComponent(firstNameJLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(activateJButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(disableJButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activateJButton)
                    .addComponent(disableJButton))
                .addGap(38, 38, 38)
                .addComponent(title1JLabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJLabel)
                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameJLabel)
                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJLabel)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passJLabel)
                    .addComponent(mainJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conPassJLabel)
                    .addComponent(confirmJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addAdminJButton)
                .addGap(45, 45, 45)
                .addComponent(backJButton)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminJButtonActionPerformed

        //Validation
        boolean validationSuccess;
        validationSuccess = validation();

        if (validationSuccess) {

            UserAccount objUserAccount = UserNameExists.userNameCheck(objWorldEnterprise, adminUserName);

            if (objUserAccount != null) {

                JOptionPane.showMessageDialog(null, "User Name already existe");
            } else {

                if (adminPassword.equals(adminConfirmPassword)) {

                    for (Organization objOrganization : objRegisteredSiteEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

                        if (objOrganization.getClass().getSimpleName().equals(Organization.OrganizationType.RegisteredSiteAdmin.getValue())) {

                            Person objPersonRegSiteAdmin = new Person(objOrganization.getClass().getSimpleName());
                            objPersonRegSiteAdmin.setPersonFirstName(adminFirstName);
                            objPersonRegSiteAdmin.setPersonLastName(adminLastName);

                            objOrganization.getObjPersonDirectory().getPersonList().add(objPersonRegSiteAdmin);
                            objOrganization.getObjUserAccountDirectory().createNewUserAccount(adminUserName, adminPassword, objPersonRegSiteAdmin, new RegSiteAdminRole(), UserAccount.StatusType.Acitve.getValue());

                            JOptionPane.showMessageDialog(null, "New admin added successfully");

                            firstNameJTextField.setText(null);
                            lastNameJTextField.setText(null);
                            userNameJTextField.setText(null);
                            mainJPasswordField.setText(null);
                            confirmJPasswordField.setText(null);

                            populateRegSiteAdminTable();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Password does not matches");
                }
            }
        }
    }//GEN-LAST:event_addAdminJButtonActionPerformed

    private boolean validation() {

        adminFirstName = firstNameJTextField.getText();
        adminLastName = lastNameJTextField.getText();
        adminUserName = userNameJTextField.getText();
        adminPassword = String.valueOf(mainJPasswordField.getPassword());
        adminConfirmPassword = String.valueOf(confirmJPasswordField.getPassword());

        if (Validation.checkForNull(adminFirstName)) {
            JOptionPane.showMessageDialog(null, "Please enter first name");
            firstNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyAlphabets(adminFirstName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper first name. It should contain only alphabets");
            firstNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForNull(adminLastName)) {
            JOptionPane.showMessageDialog(null, "Please enter last name");
            lastNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyAlphabets(adminLastName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper last name. It should contain only alphabets");
            lastNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForNull(adminUserName)) {
            JOptionPane.showMessageDialog(null, "Please enter username");
            userNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyNumAlphabets(adminUserName)) {
            JOptionPane.showMessageDialog(null, "Please enter proper username. It should contain only alphabets and numbers");
            userNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForNull(adminPassword)) {
            JOptionPane.showMessageDialog(null, "Please enter password");
            mainJPasswordField.requestFocus();
            return false;
        }

        if (Validation.checkForNull(adminConfirmPassword)) {
            JOptionPane.showMessageDialog(null, "Please enter confirm password");
            confirmJPasswordField.requestFocus();
            return false;
        }

        return true;
    }


    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void activateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateJButtonActionPerformed

        UserAccount objUserAccount = null;

        int selectedAdmin = regSiteAdminJTable.getSelectedRow();

        if (selectedAdmin < 0) {
            JOptionPane.showMessageDialog(null, "Please select an Admin");
            return;
        }

        objUserAccount = (UserAccount) regSiteAdminJTable.getValueAt(selectedAdmin, 2);

        if (objUserAccount != null) {

            if (objUserAccount.getUserAccountStatus().equals(UserAccount.StatusType.Acitve.getValue())) {
                JOptionPane.showMessageDialog(null, "Acccount is already active");
                return;
            }
            if (objUserAccount.getUserAccountStatus().equals(UserAccount.StatusType.Disabled.getValue())
                    || objUserAccount.getUserAccountStatus().equals(UserAccount.StatusType.Pending.getValue())) {

                objUserAccount.setUserAccountStatus(UserAccount.StatusType.Acitve.getValue());
                JOptionPane.showMessageDialog(null, "Acccount activated");

                populateRegSiteAdminTable();
            }
        }
    }//GEN-LAST:event_activateJButtonActionPerformed

    private void disableJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableJButtonActionPerformed

        UserAccount objUserAccount = null;

        int selectedAdmin = regSiteAdminJTable.getSelectedRow();

        if (selectedAdmin < 0) {
            JOptionPane.showMessageDialog(null, "Please select an Admin");
            return;
        }

        objUserAccount = (UserAccount) regSiteAdminJTable.getValueAt(selectedAdmin, 2);

        if (objUserAccount != null) {

            if (objUserAccount.getUserAccountStatus().equals(UserAccount.StatusType.Disabled.getValue())) {
                JOptionPane.showMessageDialog(null, "Acccount is already disabled");
                return;
            }
            if (objUserAccount.getUserAccountStatus().equals(UserAccount.StatusType.Acitve.getValue())) {

                objUserAccount.setUserAccountStatus(UserAccount.StatusType.Disabled.getValue());
                JOptionPane.showMessageDialog(null, "Acccount disabled");

                populateRegSiteAdminTable();
            }
        }
    }//GEN-LAST:event_disableJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateJButton;
    private javax.swing.JButton addAdminJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel conPassJLabel;
    private javax.swing.JPasswordField confirmJPasswordField;
    private javax.swing.JButton disableJButton;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JPasswordField mainJPasswordField;
    private javax.swing.JLabel passJLabel;
    private javax.swing.JTable regSiteAdminJTable;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel userNameJLabel;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
