/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CountryAdminRole;

import Business.CountryEnterprise.CountryEnterprise;
import Business.CountryEnterprise.CountryEnterpriseDirectory;
import Business.CountryEnterprise.RegSiteEnterprise.RegisteredSiteDirectory;
import Business.CountryEnterprise.RegSiteEnterprise.RegisteredSiteEnterprise;
import Business.Helper.CardLayoutContainer;
import Business.Helper.Validation;
import Business.Organization.RegisteredSiteAdminOrganization;
import Business.WorldEnterprise;
import UserInterface.WorldAdminRole.ManageCountryEnterpriseAdminJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageRegSiteEntJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRegSiteJPanel
     */
    private JPanel userProcessContainer;
    private CountryEnterprise objCountryEnterprise;
    private WorldEnterprise objWorldEnterprise;
    private String regSiteName;

    
    public ManageRegSiteEntJPanel(JPanel userProcessContainerPassed,
            WorldEnterprise objWorldEnterprisePassed, CountryEnterprise objCountryEnterprisePassed) {

        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objCountryEnterprise = objCountryEnterprisePassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;

        populateRegSiteTable();
    }

    private void populateRegSiteTable() {

        DefaultTableModel dtm = (DefaultTableModel) regSiteEntJTable.getModel();
        dtm.setRowCount(0);

        for (RegisteredSiteEnterprise objRegisteredSiteEnterprise : objCountryEnterprise.getObjRegisteredSiteDirectory().getRegisteredSiteList()) {

            Object row[] = new Object[2];
            row[0] = objRegisteredSiteEnterprise.getOrganizationID();
            row[1] = objRegisteredSiteEnterprise;

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        regSiteEntJTable = new javax.swing.JTable();
        title1JLabel = new javax.swing.JLabel();
        regSiteJLabel = new javax.swing.JLabel();
        regSiteNameJTextField = new javax.swing.JTextField();
        addRegSiteJButton = new javax.swing.JButton();
        mngRegSiteEntAdminJButton = new javax.swing.JButton();
        titleJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        regSiteEntJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regSiteEntJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registered Site ID", "Registered Site Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(regSiteEntJTable);
        if (regSiteEntJTable.getColumnModel().getColumnCount() > 0) {
            regSiteEntJTable.getColumnModel().getColumn(0).setResizable(false);
            regSiteEntJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        title1JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title1JLabel.setText("Add new Registered Site Enterprise");

        regSiteJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        regSiteJLabel.setText("Registered Site Name:");

        regSiteNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        regSiteNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSiteNameJTextFieldActionPerformed(evt);
            }
        });

        addRegSiteJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addRegSiteJButton.setText("Add Registered Site");
        addRegSiteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRegSiteJButtonActionPerformed(evt);
            }
        });

        mngRegSiteEntAdminJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mngRegSiteEntAdminJButton.setText("Registered Site Enterprise Admin >>");
        mngRegSiteEntAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngRegSiteEntAdminJButtonActionPerformed(evt);
            }
        });

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setText("Manage Registered Site Enterprise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(titleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(title1JLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(regSiteJLabel)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRegSiteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(regSiteNameJTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mngRegSiteEntAdminJButton)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mngRegSiteEntAdminJButton)
                .addGap(95, 95, 95)
                .addComponent(title1JLabel)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regSiteNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regSiteJLabel))
                .addGap(18, 18, 18)
                .addComponent(addRegSiteJButton)
                .addGap(63, 63, 63)
                .addComponent(backJButton)
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void regSiteNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSiteNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regSiteNameJTextFieldActionPerformed

    private void addRegSiteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRegSiteJButtonActionPerformed

        //Validation
        boolean validationSuccess;
        validationSuccess = validation();

        if (validationSuccess) {

            RegisteredSiteEnterprise objRegisteredSiteEnterprise;
            
            objRegisteredSiteEnterprise = RegisteredSiteDirectory.checkRegSiteEnterpriseExists(regSiteName, objWorldEnterprise);

            if (objRegisteredSiteEnterprise == null) {

                objRegisteredSiteEnterprise = (RegisteredSiteEnterprise) objCountryEnterprise.getObjRegisteredSiteDirectory().addRegisteredSite();
                objRegisteredSiteEnterprise.setRegSiteName(regSiteName);

                JOptionPane.showMessageDialog(null, "Registered Site added successfully");
                
                regSiteNameJTextField.setText(null);
                populateRegSiteTable();
            } else {
                JOptionPane.showMessageDialog(null, "Registered Site name already exists");
            }
        }
    }//GEN-LAST:event_addRegSiteJButtonActionPerformed

    private boolean validation() {

        regSiteName = regSiteNameJTextField.getText().trim();

        if (Validation.checkForNull(regSiteName)) {
            JOptionPane.showMessageDialog(null, "Please enter Registered Site Name");
            regSiteNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyNumAlphabets(regSiteName)) {
            JOptionPane.showMessageDialog(null, "Please enter proper name. It should contain only alphabets and numbers");
            regSiteNameJTextField.requestFocus();
            return false;
        }

        return true;
    }


    private void mngRegSiteEntAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngRegSiteEntAdminJButtonActionPerformed

        RegisteredSiteEnterprise objRegisteredSiteEnterprise;

        int selectedSiteEnterprise = regSiteEntJTable.getSelectedRow();

        if (selectedSiteEnterprise < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Site");
            return;
        }

        objRegisteredSiteEnterprise = (RegisteredSiteEnterprise) regSiteEntJTable.getValueAt(selectedSiteEnterprise, 1);

        if (objRegisteredSiteEnterprise != null) {

            ManageRegSiteEntAdminJPanel objManageRegSiteEntAdminJPanel = new ManageRegSiteEntAdminJPanel(userProcessContainer, objWorldEnterprise, objRegisteredSiteEnterprise);

            CardLayoutContainer.addNewCardLayout(userProcessContainer, "ManageRegSiteEntAdminJPanel", objManageRegSiteEntAdminJPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select again");
        }
    }//GEN-LAST:event_mngRegSiteEntAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRegSiteJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mngRegSiteEntAdminJButton;
    private javax.swing.JTable regSiteEntJTable;
    private javax.swing.JLabel regSiteJLabel;
    private javax.swing.JTextField regSiteNameJTextField;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
