/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinanceRole;

import Business.Helper.CardLayoutContainer;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorldEnterprise;
import UserInterface.ChangePasswordJPanel;
import javax.swing.JPanel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class FinanceWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinanceWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount objUserAccount;
    private WorldEnterprise objWorldEnterprise;
    private Organization objOrganization;

    public FinanceWorkAreaJPanel(JPanel userProcessContainerPassed, UserAccount objUserAccountPassed,
            WorldEnterprise objWorldEnterprisePassed, Organization objOrganizationPassed) {
        initComponents();

        this.userProcessContainer = userProcessContainerPassed;
        this.objUserAccount = objUserAccountPassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;
        this.objOrganization = objOrganizationPassed;

        loadForm();
    }

    private void loadForm() {

        nameDisplayJLabel.setText(objUserAccount.getObjPerson().toString());
        roleDisplayJLabel.setText(objUserAccount.getObjRole().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        checkDonationJButton = new javax.swing.JButton();
        overallTransactionJButton = new javax.swing.JButton();
        donateToPPJButton = new javax.swing.JButton();
        transferToRegSiteJButton = new javax.swing.JButton();
        nameJLabel = new javax.swing.JLabel();
        nameDisplayJLabel = new javax.swing.JLabel();
        roleJLabel = new javax.swing.JLabel();
        roleDisplayJLabel = new javax.swing.JLabel();
        changePasswordJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Finance Work Area");

        checkDonationJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkDonationJButton.setText("View Donation Received");
        checkDonationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDonationJButtonActionPerformed(evt);
            }
        });

        overallTransactionJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        overallTransactionJButton.setText("View Overall Transaction");
        overallTransactionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallTransactionJButtonActionPerformed(evt);
            }
        });

        donateToPPJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        donateToPPJButton.setText("Donate to PoorPeople");
        donateToPPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateToPPJButtonActionPerformed(evt);
            }
        });

        transferToRegSiteJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        transferToRegSiteJButton.setText("Money Transfer to Registered Site");
        transferToRegSiteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferToRegSiteJButtonActionPerformed(evt);
            }
        });

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nameJLabel.setText("Welcome:");

        nameDisplayJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        roleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        roleJLabel.setText("Role:");

        roleDisplayJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        changePasswordJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        changePasswordJButton.setText("Change Password >>");
        changePasswordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkDonationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donateToPPJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overallTransactionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(roleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(roleDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(229, 229, 229)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(transferToRegSiteJButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(changePasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameJLabel)
                        .addComponent(nameDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(changePasswordJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJLabel)
                    .addComponent(roleDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(titleJLabel)
                .addGap(18, 18, 18)
                .addComponent(checkDonationJButton)
                .addGap(18, 18, 18)
                .addComponent(overallTransactionJButton)
                .addGap(18, 18, 18)
                .addComponent(donateToPPJButton)
                .addGap(18, 18, 18)
                .addComponent(transferToRegSiteJButton)
                .addContainerGap(446, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donateToPPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateToPPJButtonActionPerformed

        DonateToPoorPeopleJPanel objDonateToPoorPeopleJPanel = new DonateToPoorPeopleJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "DonateToPoorPeopleJPanel", objDonateToPoorPeopleJPanel);
    }//GEN-LAST:event_donateToPPJButtonActionPerformed

    private void transferToRegSiteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferToRegSiteJButtonActionPerformed
        TransferToRegSiteJPanel objTransferToRegSiteJPanel = new TransferToRegSiteJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "TransferToRegSiteJPanel", objTransferToRegSiteJPanel);
    }//GEN-LAST:event_transferToRegSiteJButtonActionPerformed

    private void checkDonationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDonationJButtonActionPerformed

        DonationsReceivedJPanel objDonationsReceivedJPanel = new DonationsReceivedJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "DonationsReceivedJPanel", objDonationsReceivedJPanel);

    }//GEN-LAST:event_checkDonationJButtonActionPerformed

    private void overallTransactionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallTransactionJButtonActionPerformed

        OverallTransactionJPanel objOverallTransactionJPanel = new OverallTransactionJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, null, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "OverallTransactionJPanel", objOverallTransactionJPanel);
    }//GEN-LAST:event_overallTransactionJButtonActionPerformed

    private void changePasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordJButtonActionPerformed

        ChangePasswordJPanel objChangePasswordJPanel = new ChangePasswordJPanel(userProcessContainer, objUserAccount);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "ChangePasswordJPanel", objChangePasswordJPanel);
    }//GEN-LAST:event_changePasswordJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordJButton;
    private javax.swing.JButton checkDonationJButton;
    private javax.swing.JButton donateToPPJButton;
    private javax.swing.JLabel nameDisplayJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JButton overallTransactionJButton;
    private javax.swing.JLabel roleDisplayJLabel;
    private javax.swing.JLabel roleJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JButton transferToRegSiteJButton;
    // End of variables declaration//GEN-END:variables
}
