/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorldAdminRole;

import Business.CountryEnterprise.CountryEnterprise;
import Business.CountryEnterprise.CountryEnterpriseDirectory;
import Business.Helper.CardLayoutContainer;
import Business.Helper.Validation;
import Business.WorldEnterprise;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageCountryEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCountryEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private WorldEnterprise objWorldEnterprise;
    private String countryEntName;

    public ManageCountryEnterpriseJPanel(JPanel userProcessContainerPassed, WorldEnterprise objWorldEnterprisePassed) {
        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;

        populateCountryTable();
    }

    private void populateCountryTable() {

        DefaultTableModel dtm = (DefaultTableModel) countryEntJTable.getModel();
        dtm.setRowCount(0);

        for (CountryEnterprise objCountryEnterprise : objWorldEnterprise.getObjCountryEnterpriseDirectory().getCountryEnterpriseList()) {

            Object row[] = new Object[2];
            row[0] = objCountryEnterprise.getCountryID();
            row[1] = objCountryEnterprise;

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        countryEntJTable = new javax.swing.JTable();
        title1JLabel = new javax.swing.JLabel();
        countryNameJLabel = new javax.swing.JLabel();
        countryNameJTextField = new javax.swing.JTextField();
        addCountryJButton = new javax.swing.JButton();
        mngCountryEntAdminJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Manage Country Enterprise");

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        countryEntJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        countryEntJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Country ID", "Country Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(countryEntJTable);
        if (countryEntJTable.getColumnModel().getColumnCount() > 0) {
            countryEntJTable.getColumnModel().getColumn(0).setResizable(false);
            countryEntJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        title1JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title1JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1JLabel.setText("Add new Country Enterprise");

        countryNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        countryNameJLabel.setText("Country Name:");

        countryNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        countryNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryNameJTextFieldActionPerformed(evt);
            }
        });

        addCountryJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addCountryJButton.setText("Add Country");
        addCountryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCountryJButtonActionPerformed(evt);
            }
        });

        mngCountryEntAdminJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mngCountryEntAdminJButton.setText("Manage Country Enterprise Admin >>");
        mngCountryEntAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngCountryEntAdminJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(title1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(countryNameJLabel)
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addCountryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(countryNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(173, 173, 173)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mngCountryEntAdminJButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addGap(653, 653, 653))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mngCountryEntAdminJButton)
                .addGap(64, 64, 64)
                .addComponent(title1JLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryNameJLabel)
                    .addComponent(countryNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addCountryJButton)
                .addGap(124, 124, 124)
                .addComponent(backJButton)
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void countryNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryNameJTextFieldActionPerformed

    private void addCountryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCountryJButtonActionPerformed

        //Validation
        boolean validationSuccess;
        validationSuccess = validation();

        if (validationSuccess) {

            CountryEnterprise objCountryEnterprise = CountryEnterpriseDirectory.checkCountryEnterpriseExists(countryEntName, objWorldEnterprise);

            if (objCountryEnterprise == null) {

                objCountryEnterprise = (CountryEnterprise) objWorldEnterprise.getObjCountryEnterpriseDirectory().createNewCountryEnterprise();
                objCountryEnterprise.setCountryEntName(countryEntName);

                populateCountryTable();                
                JOptionPane.showMessageDialog(null, "Country added sucessfully");                
                countryNameJTextField.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Country already exists. Please check or add a proper country");
            }
        }
    }//GEN-LAST:event_addCountryJButtonActionPerformed

    
    private boolean validation() {

        countryEntName = countryNameJTextField.getText().trim();
        
        if (Validation.checkForNull(countryEntName)) {
            JOptionPane.showMessageDialog(null, "Please enter a Country Name");
            countryNameJTextField.requestFocus();
            return false;
        }
        
        if (Validation.checkForOnlyAlphabets(countryEntName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper country name. It should contain only alphabets");
            countryNameJTextField.requestFocus();
            return false;
        }
        
        return true;
    }
    
    
    private void mngCountryEntAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngCountryEntAdminJButtonActionPerformed

        CountryEnterprise objCountryEnterprise;

        int selectedCountry = countryEntJTable.getSelectedRow();

        if (selectedCountry < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Product");
            return;
        }

        objCountryEnterprise = (CountryEnterprise) countryEntJTable.getValueAt(selectedCountry, 1);

        if (objCountryEnterprise != null) {

            ManageCountryEnterpriseAdminJPanel objManageCountryEnterpriseAdminJPanel = new ManageCountryEnterpriseAdminJPanel(userProcessContainer, objWorldEnterprise, objCountryEnterprise);

            CardLayoutContainer.addNewCardLayout(userProcessContainer, "ManageCountryEnterpriseAdminJPanel", objManageCountryEnterpriseAdminJPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select again");
        }
    }//GEN-LAST:event_mngCountryEntAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCountryJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable countryEntJTable;
    private javax.swing.JLabel countryNameJLabel;
    private javax.swing.JTextField countryNameJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mngCountryEntAdminJButton;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
