/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorldAdminRole;

import Business.Helper.CardLayoutContainer;
import Business.Helper.Validation;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.WorldEnterprise;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageWorldUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserJPanel
     */
    private JPanel userProcessContainer;
    private WorldEnterprise objWorldEnterprise;
    private String firstName, lastName;

    public ManageWorldUserJPanel(JPanel userProcessContainerPassed, WorldEnterprise objWorldEnterprisePassed) {
        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;

        populateWorldOrgComboBox();
        populateWorldOrgUserComboBox();
    }

    public void populateWorldOrgComboBox() {

        worlOrgJComboBox.removeAllItems();

        for (Organization objOrganization : objWorldEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            worlOrgJComboBox.addItem(objOrganization);
        }
    }

    public void populateWorldOrgUserComboBox() {

        addUserJComboBox.removeAllItems();

        for (Organization objOrganization : objWorldEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            if (!(objOrganization instanceof DonorOrganization)) {
                addUserJComboBox.addItem(objOrganization);
            }
        }
    }

    public void populateOrgUserTable(Organization objOrganizationPassed) {

        DefaultTableModel dtm = (DefaultTableModel) userJTable.getModel();
        dtm.setRowCount(0);

        for (Person objPerson : objOrganizationPassed.getObjPersonDirectory().getPersonList()) {

            Object row[] = new Object[2];
            row[0] = objPerson.getPersonID();
            row[1] = objPerson;

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        worlOrgJComboBox = new javax.swing.JComboBox();
        addUserJComboBox = new javax.swing.JComboBox();
        lblOrganization1 = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        addUserJButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        lastNameJTextField = new javax.swing.JTextField();
        lastNameJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        worlOrgJComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        worlOrgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worlOrgJComboBoxActionPerformed(evt);
            }
        });

        addUserJComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addUserJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserJComboBoxActionPerformed(evt);
            }
        });

        lblOrganization1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblOrganization1.setText("Organization");

        firstNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstNameJLabel.setText("First Name");

        firstNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        addUserJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addUserJButton.setText("Add User");
        addUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserJButtonActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTitle.setText("Manage Persons/Users");

        lblOrganization.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblOrganization.setText("Organization");

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTitle1.setText("Add Persons/Users in Organization");

        userJTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userJTable);
        if (userJTable.getColumnModel().getColumnCount() > 0) {
            userJTable.getColumnModel().getColumn(0).setResizable(false);
            userJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        lastNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lastNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lastNameJLabel.setText("Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(105, 105, 105)
                                    .addComponent(lblOrganization)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(worlOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOrganization1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(firstNameJLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lastNameJLabel))
                                    .addGap(64, 64, 64)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addUserJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                        .addComponent(addUserJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(firstNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastNameJTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(43, 43, 43))))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(worlOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblTitle1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addUserJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameJLabel)))
                    .addComponent(lblOrganization1))
                .addGap(18, 18, 18)
                .addComponent(addUserJButton)
                .addGap(32, 32, 32)
                .addComponent(backJButton)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void worlOrgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worlOrgJComboBoxActionPerformed

        Organization objOrganization = (Organization) worlOrgJComboBox.getSelectedItem();

        if (objOrganization != null) {
            populateOrgUserTable(objOrganization);
        }
    }//GEN-LAST:event_worlOrgJComboBoxActionPerformed

    private void addUserJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserJComboBoxActionPerformed

    private void addUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserJButtonActionPerformed

        //Validation
        boolean validationSuccess;
        validationSuccess = validation();

        if (validationSuccess) {

            Organization objOrganization = (Organization) addUserJComboBox.getSelectedItem();

            if (objOrganization != null) {
                
                Person objPerson = objOrganization.getObjPersonDirectory().addPerson(objOrganization.getClass().getSimpleName());
                objPerson.setPersonFirstName(firstName);
                objPerson.setPersonLastName(lastName);

                JOptionPane.showMessageDialog(null, "User added successfully!");

                firstNameJTextField.setText(null);
                lastNameJTextField.setText(null);

                worlOrgJComboBox.setSelectedItem(objOrganization);
            }
        }
    }//GEN-LAST:event_addUserJButtonActionPerformed

    private boolean validation() {

        firstName = firstNameJTextField.getText().trim();
        lastName = lastNameJTextField.getText().trim();

        if (Validation.checkForNull(firstName)) {
            JOptionPane.showMessageDialog(null, "Please enter first name");
            firstNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyAlphabets(firstName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper first name. It should contain only alphabets");
            firstNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForNull(lastName)) {
            JOptionPane.showMessageDialog(null, "Please enter last name");
            lastNameJTextField.requestFocus();
            return false;
        }

        if (Validation.checkForOnlyAlphabets(lastName)) {
            JOptionPane.showMessageDialog(null, "Please enter a proper last name. It should contain only alphabets");
            lastNameJTextField.requestFocus();
            return false;
        }

        return true;
    }


    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserJButton;
    private javax.swing.JComboBox addUserJComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblOrganization1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable userJTable;
    private javax.swing.JComboBox worlOrgJComboBox;
    // End of variables declaration//GEN-END:variables
}
