/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorldAdminRole;

import Business.Helper.CardLayoutContainer;
import Business.Organization.Organization;
import Business.WorldEnterprise;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageWorldOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWorldOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private WorldEnterprise objWorldEnterprise;

    public ManageWorldOrganizationJPanel(JPanel userProcessContainerPassed, WorldEnterprise objWorldEnterprisePassed) {
        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;

        populateWorldOrgTable();
        populateWorldOrgComboBox();
    }

    private void populateWorldOrgTable() {

        DefaultTableModel dtm = (DefaultTableModel) worldOrgJTable.getModel();
        dtm.setRowCount(0);

        for (Organization objOrganization : objWorldEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            Object row[] = new Object[2];
            row[0] = objOrganization.getOrganizationID();
            row[1] = objOrganization;

            dtm.addRow(row);
        }
    }

    private void populateWorldOrgComboBox() {

        worlOrgJComboBox.removeAllItems();

        for (Organization.OrganizationType orgType : Organization.OrganizationType.values()) {

            if (orgType.getValue().equals(Organization.OrganizationType.Finance.getValue())
                    || orgType.getValue().equals(Organization.OrganizationType.Support.getValue())) {

                worlOrgJComboBox.addItem(orgType);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        worldOrgJTable = new javax.swing.JTable();
        title1JLabel = new javax.swing.JLabel();
        orgJLabel = new javax.swing.JLabel();
        worlOrgJComboBox = new javax.swing.JComboBox();
        addWorldOrgJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        titleJLabel.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Manage Organization");

        worldOrgJTable.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        worldOrgJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization ID", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(worldOrgJTable);
        if (worldOrgJTable.getColumnModel().getColumnCount() > 0) {
            worldOrgJTable.getColumnModel().getColumn(0).setResizable(false);
            worldOrgJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        title1JLabel.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        title1JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1JLabel.setText("Add Organization");

        orgJLabel.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        orgJLabel.setText("Organization Type:");

        worlOrgJComboBox.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        worlOrgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worlOrgJComboBoxActionPerformed(evt);
            }
        });

        addWorldOrgJButton.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        addWorldOrgJButton.setText("Add Organization");
        addWorldOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWorldOrgJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addWorldOrgJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backJButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(orgJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(worlOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titleJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(title1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleJLabel)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(title1JLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(worlOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgJLabel))
                .addGap(18, 18, 18)
                .addComponent(addWorldOrgJButton)
                .addGap(105, 105, 105)
                .addComponent(backJButton)
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void worlOrgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worlOrgJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_worlOrgJComboBoxActionPerformed

    private void addWorldOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWorldOrgJButtonActionPerformed

        boolean isOrgPresent = false;

        if (worlOrgJComboBox.getItemCount() != 0) {

            Organization.OrganizationType orgTypeSelected = (Organization.OrganizationType) worlOrgJComboBox.getSelectedItem();

            for (Organization objOrgPresent : objWorldEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

                if (objOrgPresent.getClass().getSimpleName().equals(orgTypeSelected.getValue())) {

                    JOptionPane.showMessageDialog(null, "Organization already exists");
                    isOrgPresent = true;
                    return;
                }
            }

            if (!isOrgPresent) {

                objWorldEnterprise.getObjOrganizationDirectory().addOrganization(orgTypeSelected);
                JOptionPane.showMessageDialog(null, "Organization added successfully");
                populateWorldOrgTable();
            }
        }
    }//GEN-LAST:event_addWorldOrgJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWorldOrgJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgJLabel;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JComboBox worlOrgJComboBox;
    private javax.swing.JTable worldOrgJTable;
    // End of variables declaration//GEN-END:variables
}
