/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorldAdminRole;

import Business.Helper.CardLayoutContainer;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorldEnterprise;
import UserInterface.ChangePasswordJPanel;
import UserInterface.FinanceRole.DonateToPoorPeopleJPanel;
import UserInterface.FinanceRole.DonationsReceivedJPanel;
import UserInterface.FinanceRole.OverallTransactionJPanel;
import UserInterface.FinanceRole.TransferToRegSiteJPanel;
import javax.swing.JPanel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class WorldAdminWorkAreaJPanelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorldAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount objUserAccount;
    private WorldEnterprise objWorldEnterprise;
    private Organization objOrganization;

    public WorldAdminWorkAreaJPanelJPanel(JPanel userProcessContainerPassed,
            WorldEnterprise objWorldEnterprisePassed, UserAccount objUserAccountPassed,
            Organization objOrganizationPassed) {
        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objUserAccount = objUserAccountPassed;
        this.objWorldEnterprise = objWorldEnterprisePassed;
        this.objOrganization = objOrganizationPassed;

        loadForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        mngCountryEntJButton = new javax.swing.JButton();
        mngOrganizationJButton = new javax.swing.JButton();
        mngUserJButton = new javax.swing.JButton();
        mngUserAcountJButton = new javax.swing.JButton();
        checkDonationJButton = new javax.swing.JButton();
        overallTransactionJButton = new javax.swing.JButton();
        donateToPPJButton = new javax.swing.JButton();
        transferToRegSiteJButton = new javax.swing.JButton();
        nameJLabel = new javax.swing.JLabel();
        nameDisplayJLabel = new javax.swing.JLabel();
        roleJLabel = new javax.swing.JLabel();
        roleDisplayJLabel = new javax.swing.JLabel();
        titleJLabel1 = new javax.swing.JLabel();
        titleJLabel2 = new javax.swing.JLabel();
        changePasswordJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Work Area");

        mngCountryEntJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mngCountryEntJButton.setText("Manage Country Enterprise");
        mngCountryEntJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngCountryEntJButtonActionPerformed(evt);
            }
        });

        mngOrganizationJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mngOrganizationJButton.setText("Manage World Organization");
        mngOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngOrganizationJButtonActionPerformed(evt);
            }
        });

        mngUserJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mngUserJButton.setText("Manage User");
        mngUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngUserJButtonActionPerformed(evt);
            }
        });

        mngUserAcountJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mngUserAcountJButton.setText("Manage  User Account");
        mngUserAcountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngUserAcountJButtonActionPerformed(evt);
            }
        });

        checkDonationJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkDonationJButton.setText("View Donation Received");
        checkDonationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDonationJButtonActionPerformed(evt);
            }
        });

        overallTransactionJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        overallTransactionJButton.setText("View Overall Transaction");
        overallTransactionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallTransactionJButtonActionPerformed(evt);
            }
        });

        donateToPPJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        donateToPPJButton.setText("Donation made to Poor People");
        donateToPPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateToPPJButtonActionPerformed(evt);
            }
        });

        transferToRegSiteJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        transferToRegSiteJButton.setText("Money Transfered to Registered Site");
        transferToRegSiteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferToRegSiteJButtonActionPerformed(evt);
            }
        });

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nameJLabel.setText("Welcome:");

        nameDisplayJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        roleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        roleJLabel.setText("Role:");

        roleDisplayJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        titleJLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel1.setText("View");

        titleJLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel2.setText("Manage");

        changePasswordJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        changePasswordJButton.setText("Change Password >>");
        changePasswordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(roleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(roleDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(changePasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mngOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mngCountryEntJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mngUserJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mngUserAcountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleJLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(transferToRegSiteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donateToPPJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(overallTransactionJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkDonationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameJLabel)
                        .addComponent(nameDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(changePasswordJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJLabel)
                    .addComponent(roleDisplayJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(titleJLabel)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleJLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(checkDonationJButton)
                        .addGap(18, 18, 18)
                        .addComponent(overallTransactionJButton)
                        .addGap(18, 18, 18)
                        .addComponent(donateToPPJButton)
                        .addGap(18, 18, 18)
                        .addComponent(transferToRegSiteJButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleJLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mngCountryEntJButton)
                        .addGap(18, 18, 18)
                        .addComponent(mngOrganizationJButton)
                        .addGap(18, 18, 18)
                        .addComponent(mngUserJButton)
                        .addGap(18, 18, 18)
                        .addComponent(mngUserAcountJButton)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadForm() {

        nameDisplayJLabel.setText(objUserAccount.getObjPerson().toString());
        roleDisplayJLabel.setText(objUserAccount.getObjRole().toString());
    }

    private void mngCountryEntJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngCountryEntJButtonActionPerformed

        ManageCountryEnterpriseJPanel objManageCountryEnterpriseJPanel = new ManageCountryEnterpriseJPanel(userProcessContainer, objWorldEnterprise);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "ManageCountryEnterpriseJPanel", objManageCountryEnterpriseJPanel);
    }//GEN-LAST:event_mngCountryEntJButtonActionPerformed

    private void mngOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngOrganizationJButtonActionPerformed

        ManageWorldOrganizationJPanel objManageWorldOrganizationJPanel = new ManageWorldOrganizationJPanel(userProcessContainer, objWorldEnterprise);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "ManageWorldOrganizationJPanel", objManageWorldOrganizationJPanel);
    }//GEN-LAST:event_mngOrganizationJButtonActionPerformed

    private void mngUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngUserJButtonActionPerformed

        ManageWorldUserJPanel objManageWorldUserJPanel = new ManageWorldUserJPanel(userProcessContainer, objWorldEnterprise);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "ManageWorldUserJPanel", objManageWorldUserJPanel);
    }//GEN-LAST:event_mngUserJButtonActionPerformed

    private void mngUserAcountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngUserAcountJButtonActionPerformed

        ManageWorldUserAccountJPanel objManageWorldUserAccountJPanel = new ManageWorldUserAccountJPanel(userProcessContainer, objWorldEnterprise, objOrganization, objUserAccount);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "ManageWorldUserAccountJPanel", objManageWorldUserAccountJPanel);
    }//GEN-LAST:event_mngUserAcountJButtonActionPerformed

    private void checkDonationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDonationJButtonActionPerformed

        DonationsReceivedJPanel objDonationsReceivedJPanel = new DonationsReceivedJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "DonationsReceivedJPanel", objDonationsReceivedJPanel);

    }//GEN-LAST:event_checkDonationJButtonActionPerformed

    private void overallTransactionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallTransactionJButtonActionPerformed

        OverallTransactionJPanel objOverallTransactionJPanel = new OverallTransactionJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, null, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "OverallTransactionJPanel", objOverallTransactionJPanel);
    }//GEN-LAST:event_overallTransactionJButtonActionPerformed

    private void donateToPPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateToPPJButtonActionPerformed

        DonateToPoorPeopleJPanel objDonateToPoorPeopleJPanel = new DonateToPoorPeopleJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "DonateToPoorPeopleJPanel", objDonateToPoorPeopleJPanel);
    }//GEN-LAST:event_donateToPPJButtonActionPerformed

    private void transferToRegSiteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferToRegSiteJButtonActionPerformed
        TransferToRegSiteJPanel objTransferToRegSiteJPanel = new TransferToRegSiteJPanel(userProcessContainer, objUserAccount, objWorldEnterprise, objOrganization);

        CardLayoutContainer.addNewCardLayout(userProcessContainer, "TransferToRegSiteJPanel", objTransferToRegSiteJPanel);
    }//GEN-LAST:event_transferToRegSiteJButtonActionPerformed

    private void changePasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordJButtonActionPerformed

        ChangePasswordJPanel objChangePasswordJPanel = new ChangePasswordJPanel(userProcessContainer, objUserAccount);
        
        CardLayoutContainer.addNewCardLayout(userProcessContainer, "ChangePasswordJPanel", objChangePasswordJPanel);
    }//GEN-LAST:event_changePasswordJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordJButton;
    private javax.swing.JButton checkDonationJButton;
    private javax.swing.JButton donateToPPJButton;
    private javax.swing.JButton mngCountryEntJButton;
    private javax.swing.JButton mngOrganizationJButton;
    private javax.swing.JButton mngUserAcountJButton;
    private javax.swing.JButton mngUserJButton;
    private javax.swing.JLabel nameDisplayJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JButton overallTransactionJButton;
    private javax.swing.JLabel roleDisplayJLabel;
    private javax.swing.JLabel roleJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel titleJLabel1;
    private javax.swing.JLabel titleJLabel2;
    private javax.swing.JButton transferToRegSiteJButton;
    // End of variables declaration//GEN-END:variables
}
