/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FieldExpertRole;

import Business.Helper.CardLayoutContainer;
import Business.Person.Person;
import Business.Person.PoorPeople.FamilyMember;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PPVerificationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class VerifyPoorPeopleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerififyPoorPeopleJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount objUserAccount;
    private PPVerificationWorkRequest objPPVerificationWorkRequest;
    private Person objPerson;

    public VerifyPoorPeopleJPanel(JPanel userProcessContainerPassed, UserAccount objUserAccountPassed,
            PPVerificationWorkRequest objPPVerificationWorkRequestPassed) {
        initComponents();

        this.userProcessContainer = userProcessContainerPassed;
        this.objUserAccount = objUserAccountPassed;
        this.objPPVerificationWorkRequest = objPPVerificationWorkRequestPassed;
        this.objPerson = objPPVerificationWorkRequest.getObjPerson();

        populateFields();
    }

    private void populateFields() {

        ppFirstNameJTextField.setText(objPerson.getPersonFirstName());
        ppLastNameJTextField.setText(objPerson.getPersonLastName());
        ppIntIdJTextField.setText(objPerson.getPersonInternationalID());
        ppDobJTextField.setText(objPerson.getPersonDateOfBirth());
        ppSexTextField.setText(objPerson.getPersonSex());
        ppAdd1JTextField.setText(objPerson.getPersonAddress1());
        ppAdd2JTextField.setText(objPerson.getPersonAddress2());
        ppCountryJTextField.setText(objPerson.getPersonCountry());
        ppStateJTextField.setText(objPerson.getPersonState());
        ppCityJTextField.setText(objPerson.getPersonCity());
        ppPinCodeJTextField.setText(objPerson.getPersonPinCode());

        houseConditionJTextField.setText(objPerson.getPersonHouseCondition());
        houseTypeJTextField.setText(objPerson.getPersonHouseType());
        houseLatLonJTextField.setText(objPerson.getPersonHouseLatitude() + ", " + objPerson.getPersonHouseLongitude());

        populateFamilyTable(objPerson.getObjFamilyMemberDirectory().getFamilyMemberList());
    }

    private void populateFamilyTable(ArrayList<FamilyMember> familyMemberListPassed) {

        DefaultTableModel dtm = (DefaultTableModel) fmJTable.getModel();
        dtm.setRowCount(0);

        for (FamilyMember objFamilyMember : familyMemberListPassed) {

            Object row[] = new Object[3];
            row[0] = objFamilyMember.getMemberInternationalID();
            row[1] = objFamilyMember;
            row[2] = objFamilyMember.getMemberRelation();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        ppDobJTextField = new javax.swing.JTextField();
        sexJLabel = new javax.swing.JLabel();
        add1JLabel = new javax.swing.JLabel();
        ppAdd1JTextField = new javax.swing.JTextField();
        add2JLabel = new javax.swing.JLabel();
        ppAdd2JTextField = new javax.swing.JTextField();
        cityJLabel = new javax.swing.JLabel();
        ppCityJTextField = new javax.swing.JTextField();
        stateJLabel = new javax.swing.JLabel();
        ppStateJTextField = new javax.swing.JTextField();
        countryJLabel = new javax.swing.JLabel();
        ppCountryJTextField = new javax.swing.JTextField();
        pinJLabel = new javax.swing.JLabel();
        ppPinCodeJTextField = new javax.swing.JTextField();
        title2JLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        ppIntIdJTextField = new javax.swing.JTextField();
        fNameJLabel = new javax.swing.JLabel();
        ppFirstNameJTextField = new javax.swing.JTextField();
        lNameJLabel = new javax.swing.JLabel();
        ppLastNameJTextField = new javax.swing.JTextField();
        ppSexTextField = new javax.swing.JTextField();
        title3JLabel = new javax.swing.JLabel();
        hTypeJLabel = new javax.swing.JLabel();
        hCondJLabel = new javax.swing.JLabel();
        hLatLonJLabel = new javax.swing.JLabel();
        houseLatLonJTextField = new javax.swing.JTextField();
        houseTypeJTextField = new javax.swing.JTextField();
        houseConditionJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fmJTable = new javax.swing.JTable();
        title4JLabel = new javax.swing.JLabel();
        checkMapJButton = new javax.swing.JButton();
        disapproveJButton = new javax.swing.JButton();
        approveJButton = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleJLabel.setText("Verify User");

        dobJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dobJLabel.setText("Date of Birth:");

        ppDobJTextField.setEditable(false);
        ppDobJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        sexJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sexJLabel.setText("Sex:");

        add1JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        add1JLabel.setText("Address 1:");

        ppAdd1JTextField.setEditable(false);
        ppAdd1JTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        add2JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        add2JLabel.setText("Address 2:");

        ppAdd2JTextField.setEditable(false);
        ppAdd2JTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        cityJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cityJLabel.setText("Village / City:");

        ppCityJTextField.setEditable(false);
        ppCityJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        stateJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        stateJLabel.setText("State:");

        ppStateJTextField.setEditable(false);
        ppStateJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        countryJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        countryJLabel.setText("Country:");

        ppCountryJTextField.setEditable(false);
        ppCountryJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        pinJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pinJLabel.setText("Pin Code:");

        ppPinCodeJTextField.setEditable(false);
        ppPinCodeJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        title2JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title2JLabel.setText("Personnel Details");

        idJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idJLabel.setText("International ID:");

        ppIntIdJTextField.setEditable(false);
        ppIntIdJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        fNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fNameJLabel.setText("First Name:");

        ppFirstNameJTextField.setEditable(false);
        ppFirstNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lNameJLabel.setText("Last Name:");

        ppLastNameJTextField.setEditable(false);
        ppLastNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        ppSexTextField.setEditable(false);
        ppSexTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        title3JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title3JLabel.setText("House Details");

        hTypeJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hTypeJLabel.setText("Type:");

        hCondJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hCondJLabel.setText("Condition:");

        hLatLonJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hLatLonJLabel.setText("Latitude & Longitude:");

        houseLatLonJTextField.setEditable(false);
        houseLatLonJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        houseTypeJTextField.setEditable(false);
        houseTypeJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        houseConditionJTextField.setEditable(false);
        houseConditionJTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        fmJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fmJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "International ID", "Name", "Relation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fmJTable);
        if (fmJTable.getColumnModel().getColumnCount() > 0) {
            fmJTable.getColumnModel().getColumn(0).setResizable(false);
            fmJTable.getColumnModel().getColumn(1).setResizable(false);
            fmJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        title4JLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        title4JLabel.setText("Family Details");

        checkMapJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkMapJButton.setText("Check Google Maps >>");
        checkMapJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMapJButtonActionPerformed(evt);
            }
        });

        disapproveJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        disapproveJButton.setText("Dis-Approve");
        disapproveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disapproveJButtonActionPerformed(evt);
            }
        });

        approveJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        backJButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(backJButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pinJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ppFirstNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppIntIdJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppLastNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppDobJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppAdd2JTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppCityJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppCountryJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppStateJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppPinCodeJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppSexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppAdd1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(approveJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(title2JLabel, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hCondJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hTypeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hLatLonJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(houseTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(houseConditionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(houseLatLonJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(title3JLabel)))
                                    .addComponent(checkMapJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(disapproveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(title4JLabel)))
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(titleJLabel)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backJButton2)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title2JLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(title3JLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(houseTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hTypeJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(houseConditionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hCondJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(houseLatLonJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hLatLonJLabel))
                                .addGap(25, 25, 25)
                                .addComponent(title4JLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(checkMapJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ppIntIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppFirstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fNameJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppLastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNameJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppDobJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppSexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppAdd1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add1JLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppAdd2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add2JLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppCityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityJLabel))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppStateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppCountryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ppPinCodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pinJLabel))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(approveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(disapproveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(148, 148, 148))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkMapJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMapJButtonActionPerformed

        try {
            String lat = objPPVerificationWorkRequest.getObjPerson().getPersonHouseLatitude();
            String lon = objPPVerificationWorkRequest.getObjPerson().getPersonHouseLongitude();
            String zoom = "18z";

            String finalURL = "https://www.google.com.au/maps/preview/@" + lat + "," + lon + "," + zoom;

            System.out.println(finalURL);

            java.awt.Desktop.getDesktop().browse(java.net.URI.create(finalURL));

        } catch (Exception exe) {
            System.out.println(exe);
        }
    }//GEN-LAST:event_checkMapJButtonActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to Approve this user?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {

            objPerson.setPersonStatus(Person.PersonRegStatusType.Approved.getValue());
            objPPVerificationWorkRequest.setStatus(WorkRequest.WorkRequestStatus.COMPLETED.getValue());
            objPPVerificationWorkRequest.setMessage("Person Approved");

            JOptionPane.showMessageDialog(null, "Person Approved successfully");

            CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
        }
    }//GEN-LAST:event_approveJButtonActionPerformed

    private void disapproveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disapproveJButtonActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to Dis-Approve this user?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            objPerson.setPersonStatus(Person.PersonRegStatusType.DisApproved.getValue());
            objPPVerificationWorkRequest.setStatus(WorkRequest.WorkRequestStatus.COMPLETED.getValue());
            objPPVerificationWorkRequest.setMessage("Person Dis-Approved");

            JOptionPane.showMessageDialog(null, "Person Dis-Approved successfully");

            CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
        }
    }//GEN-LAST:event_disapproveJButtonActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add1JLabel;
    private javax.swing.JLabel add2JLabel;
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton backJButton2;
    private javax.swing.JButton checkMapJButton;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JButton disapproveJButton;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel fNameJLabel;
    private javax.swing.JTable fmJTable;
    private javax.swing.JLabel hCondJLabel;
    private javax.swing.JLabel hLatLonJLabel;
    private javax.swing.JLabel hTypeJLabel;
    private javax.swing.JTextField houseConditionJTextField;
    private javax.swing.JTextField houseLatLonJTextField;
    private javax.swing.JTextField houseTypeJTextField;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNameJLabel;
    private javax.swing.JLabel pinJLabel;
    private javax.swing.JTextField ppAdd1JTextField;
    private javax.swing.JTextField ppAdd2JTextField;
    private javax.swing.JTextField ppCityJTextField;
    private javax.swing.JTextField ppCountryJTextField;
    private javax.swing.JTextField ppDobJTextField;
    private javax.swing.JTextField ppFirstNameJTextField;
    private javax.swing.JTextField ppIntIdJTextField;
    private javax.swing.JTextField ppLastNameJTextField;
    private javax.swing.JTextField ppPinCodeJTextField;
    private javax.swing.JTextField ppSexTextField;
    private javax.swing.JTextField ppStateJTextField;
    private javax.swing.JLabel sexJLabel;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JLabel title2JLabel;
    private javax.swing.JLabel title3JLabel;
    private javax.swing.JLabel title4JLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
