/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RegSiteAdminRole;

import Business.CountryEnterprise.RegSiteEnterprise.RegisteredSiteEnterprise;
import Business.Helper.CardLayoutContainer;
import Business.Organization.Organization;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author "Smit Shah, NUID: 001748537, AED - Final Project"
 */
public class ManageRegSiteOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRegSiteOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private RegisteredSiteEnterprise objRegisteredSiteEnterprise;

    public ManageRegSiteOrganizationJPanel(JPanel userProcessContainerPassed,
            RegisteredSiteEnterprise objRegisteredSiteEnterprisePassed) {

        initComponents();
        this.userProcessContainer = userProcessContainerPassed;
        this.objRegisteredSiteEnterprise = objRegisteredSiteEnterprisePassed;

        populateRegSiteOrgTable();
        populateregSiteOrgComboBox();
    }

    private void populateRegSiteOrgTable() {

        DefaultTableModel dtm = (DefaultTableModel) regSiteOrgJTable.getModel();
        dtm.setRowCount(0);

        for (Organization objOrganization : objRegisteredSiteEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

            Object row[] = new Object[2];
            row[0] = objOrganization.getOrganizationID();
            row[1] = objOrganization;

            dtm.addRow(row);
        }
    }

    private void populateregSiteOrgComboBox() {

        regSiteOrgJComboBox.removeAllItems();

        for (Organization.OrganizationType orgType : Organization.OrganizationType.values()) {

            if (orgType.getValue().equals(Organization.OrganizationType.RegisteredSiteAgent.getValue())) {

                regSiteOrgJComboBox.addItem(orgType);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        lblOrgType = new javax.swing.JLabel();
        regSiteOrgJComboBox = new javax.swing.JComboBox();
        addOrgJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        regSiteOrgJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Add Organization");

        lblOrgType.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblOrgType.setText("Organization Type:");

        regSiteOrgJComboBox.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        regSiteOrgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSiteOrgJComboBoxActionPerformed(evt);
            }
        });

        addOrgJButton.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        addOrgJButton.setText("Add Organization");
        addOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblTitle.setText("Manage Organization");

        regSiteOrgJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regSiteOrgJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization ID", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(regSiteOrgJTable);
        if (regSiteOrgJTable.getColumnModel().getColumnCount() > 0) {
            regSiteOrgJTable.getColumnModel().getColumn(0).setResizable(false);
            regSiteOrgJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(backJButton))
                                    .addComponent(lblOrgType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(regSiteOrgJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addOrgJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrgType)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regSiteOrgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addOrgJButton)))
                .addGap(127, 127, 127)
                .addComponent(backJButton)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regSiteOrgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSiteOrgJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regSiteOrgJComboBoxActionPerformed

    private void addOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgJButtonActionPerformed

        boolean isOrgPresent = false;

        if (regSiteOrgJComboBox.getItemCount() != 0) {

            Organization.OrganizationType orgTypeSelected = (Organization.OrganizationType) regSiteOrgJComboBox.getSelectedItem();
            System.out.println("Org selected ->" + orgTypeSelected);

            for (Organization objOrgPresent : objRegisteredSiteEnterprise.getObjOrganizationDirectory().getOrganizationList()) {

                System.out.println("Org present ->" + objOrgPresent);
                if (objOrgPresent.getClass().getSimpleName().equals(orgTypeSelected.getValue())) {

                    JOptionPane.showMessageDialog(null, "Organization already exists");
                    isOrgPresent = true;
                    return;
                }
            }

            if (!isOrgPresent) {

                objRegisteredSiteEnterprise.getObjOrganizationDirectory().addOrganization(orgTypeSelected);
                JOptionPane.showMessageDialog(null, "Organization added successfully");
                populateRegSiteOrgTable();
            }
        }
    }//GEN-LAST:event_addOrgJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayoutContainer.removeCurrentCardLayout(userProcessContainer, this);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrgJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JComboBox regSiteOrgJComboBox;
    private javax.swing.JTable regSiteOrgJTable;
    // End of variables declaration//GEN-END:variables
}
